apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopeasy
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: shopeasy
        image: juhisinha/shopeasy:v1
        ports:
        - containerPort: 5000
